Swatinem/rust-cache

README.md, src/common.ts
These project override files aren't frequently used, but when they are the cache should definitely key on them to catch changes that may not be reflected in `Cargo.toml` alone.
See https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
=> Additionally key on Rust toolchain file(s) if present

README.md
Hey @Swatinem, thank you for this awesome project!
Disclaimer: I'm not very experienced either with GitHub actions or rust, so this might be an incorrect change -- feel free to ignore the PR if so.
As far as my experience with this action goes, it does not seem to do anything if the repo gets checked out *after* the cache setup. Placing the `actions/checkout` step before the `rust-cache` step seems to solve the problem though. So
```yml
- uses: actions-rs/toolchain@v1
with:
profile: minimal
toolchain: stable
- uses: Swatinem/rust-cache@v1
- uses: actions/checkout@v2 # checkout at the end
```
```yml
- uses: actions/checkout@v2 # checkout at the top
- uses: actions-rs/toolchain@v1
with:
profile: minimal
toolchain: stable
- uses: Swatinem/rust-cache@v1
```
It might be a common practice in …
=> hint that checkout has to be done first

README.md
Thank you for a great tool!
This updates the documentation on how the cache works to more closely match the implementation and to explain some of the design decisions.
In addition, I've made a few wording/detail tweaks based on questions I had when first using this action, that had to be answered by source code inspection. (For example: "is the cache key only based off of the repo root `Cargo.toml` / `Cargo.lock` or all such files in the repository, including subdirectories?".)
=> Improve Cache Details documentation

src/restore.ts, src/save.ts
Also add logging to the quiet exception handlers.
Before:
After:
I also considered adding source maps:
but it increases the size of `dist/` from 5MB to 10MB, and what's worse, source-maps are not diff-friendly, so minor changes will take a lot of space in the repository.
So I decided against that. Navigating non-minified `index.js` is tolerable.
----
I didn't include update to `dist/` in this PR, because I got the impression that you prefer to do it yourself.
=> Improve diagnostics: show exception stack trace

src/save.ts
This fixes #64.
When Cargo is run in sparse-registry mode, it doesn't create
~/.cargo/registry/index/github.com-1ecc6299db9ec823/
directory.
=> Skip registry cleaning if no registry was found

package-lock.json, package.json
According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ this should fix the deprecations warnings related to `save-state` and `set-output`.
=> Update `@actions/cors` to v1.10.0

README.md, action.yml, dist/restore/index.js, dist/save/index.js, src/config.ts
rust-cache currently stores a target directory even if a shared compilation cache such as  [sccache](github.com/mozilla/sccache) is used.
Added `prefix-key` `cache-directories` and `cache-targets` options allows more control over what compilation artifacts to cache.
=> Added `prefix-key` `cache-directories` and `cache-targets` options

README.md, action.yml, dist/restore/index.js, dist/save/index.js, src/cleanup.ts, src/save.ts
Add cache-all-crates option which allows all crates to be cached instead of just the dependency crates. This is useful when additional crates are required for CI tooling.
Fixes #134
=> feat: add option to cache all crates

.github/workflows/check-dist.yml, package-lock.json, package.json
Use linefix so that when developing changes the results of `npm run prepare` always have unix line endings so `git diff` commands don't show line ending changes for the `ncc` generated files.
=> chore: use linefix to ensure platform line endings

CHANGELOG.md, dist/restore/index.js, dist/save/index.js, src/config.ts
Use 8 character hash components to reduce the key length, making it more readable.
Fixes #97
=> chore: use 8 character hash components

dist/restore/index.js, dist/save/index.js, package-lock.json, package.json, src/config.ts
Fixed #146
- Set all `package.version` in `Cargo.toml` to `0.0.0`
- Set `{build-, dev-, }dependencies` of workspace crates to `0.0.0`
- Remove workspace crates from `Cargo.lock` before caching
- Sort all toml objects before hashing them as json
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> feat: Rm workspace crates version before caching

dist/restore/index.js, dist/save/index.js, src/config.ts
Also:
- Add and use `sort_and_uniq` to make sure `globFile` resulting and `keyFiles` does not contain duplicates.
- Only returns regular file in function `globFile`
=> feat: Add hash of `.cargo/config.toml` to key

dist/restore/index.js, dist/save/index.js, src/config.ts
Fixed #151
I've tried running manually load and parse `Cargo.lock` and it runs fine until `sort_object` is called.
Since `Cargo.lock` is auto-generated and usually sorted, I think there is no need for sorting.
=> fix `src/config.ts`: Remove `sort_object`

dist/restore/index.js, dist/save/index.js, src/config.ts
There are a few problems in cargo-binstall where sometimes change to `Cargo.lock` does not invalidate the cache.
=> feat: Add logging to `Cargo.lock`/`Cargo.toml` hashing

dist/restore/index.js, dist/save/index.js, src/config.ts
This simple mistake caused the entire `Cargo.lock` to be ignored (JS treats having no return as `false`).
=> Fix typo in hashing parsed `Cargo.lock`

dist/restore/index.js, dist/save/index.js, src/config.ts
The values for the dependencies could be strings intead of objects, so add a `try` block to take care of that.
Also set `dep.path` to `""` if the dependency contains a key `path` to make sure that the cache isn't invalidated due to change in workspace.
=> Fix hashing of parsed `Cargo.toml`

dist/restore/index.js, dist/save/index.js, package-lock.json, package.json, src/config.ts
Fixed #162 #163
The former is listed on
https://github.com/toml-lang/toml/wiki#implementations and is toml 1.0 compliant.
=> dep: Use `smol-toml` instead of `toml`

README.md
closes https://github.com/Swatinem/rust-cache/issues/165
Details are in the issue.
=> Fix save-if documentation in readme

dist/restore/index.js, dist/save/index.js, src/cleanup.ts, src/config.ts, src/save.ts, src/utils.ts, src/workspace.ts
Currently, we glob for all `Cargo.toml` and `Cargo.lock` files anywhere in a workspace, but this can pick up false positives (see #179). This PR switches to only using `Cargo.toml` files of workspace members (determined using [`cargo metadata --no-deps`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options)) and per-workspace `Cargo.lock` files.
Closes #179
=> Only key by `Cargo.toml` and `Cargo.lock` files of workspace members

.github/workflows/buildjet.yml, .github/workflows/check-dist.yml, .github/workflows/coverage.yml, .github/workflows/git-registry.yml, .github/workflows/install.yml, .github/workflows/simple.yml, .github/workflows/target-dir.yml, .github/workflows/workspaces.yml, README.md
This fixes issue #189.
This is necessary because GitHub actions are going to drop support for Node.js 16. Version 4 uses Node.js 20.
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Upgrade checkout action from version 3 to 4

.github/workflows/check-dist.yml
=> fix: usage of `deprecated` version of `node`

dist/save/index.js, src/save.ts
Currently, when you run a workflow using ubuntu-latest and this action through [nektos/act](https://github.com/nektos/act), it will hang during the save process due to `sudo` awaiting user input because `/usr/sbin/purge` isn't found (meaning you'll have to exec into the container and kill this sudo process to make it move on).
This change makes it only try to run purge if you're actually on a macOS runner.
=> Only run macOsWorkaround() on macOS

dist/restore/index.js, dist/save/index.js, src/config.ts
=> Support Cargo.lock format cargo-lock v4

dist/restore/index.js, dist/save/index.js, src/config.ts
=> add runner OS in cache key

dist/restore/index.js, dist/save/index.js, src/config.ts
GitHub [announced](https://github.blog/changelog/2024-06-24-github-actions-ubuntu-24-04-image-now-available-for-arm64-runners/) Linux arm64 hosted runners.
Now GitHub Actions supports both x86_64 and arm64 for Linux. However rust-cache action doesn't include the CPU arch in the cache key. For example:
```
v0-rust-unit-test-Linux-ec67c29d-227d31a8
```
This PR includes CPU arch in the generated cache key so that it can ensure different caches are created on different CPU architectures and they are not mixed up.
=> Include CPU arch in the cache key for arm64 Linux runners

README.md, action.yml, dist/save/index.js, src/save.ts
The default caching strategy is to exclude workspace crates, which makes sense for small workspaces, but in cases where the workspace contains libraries which are hardly changed it is nicer to cache the workspace creates as well. This PR adds that option.
Note that setting `cache-all-crates = true` makes `cache-workspace-crates` irrelevant, in principle there are only three options now (only dependencies, dependencies+workspace, all), but to keep things backwards compatible I did not want to change the existing options, so I think adding this should be fine.
=> Add cache-workspace-crates feature

src/workspace.ts
https://github.com/oli-obk/cargo_metadata/issues/290
> Most likely because Rust has recently tightened up some of the checks in the compiler.
=> Set empty `CARGO_ENCODED_RUSTFLAGS` in workspace metadata retrieval

.github/workflows/dependabot.yml
- dependabot auto-merge regenerates and commits dist/ if changed
=> chore(dependabot): regenerate and commit dist/
